services:
  api-gateway:
    build: .
    ports:
      - "7878:7878"
    environment:
      - GRPC_USER_SERVICE_ADDR=user-service:7373
      - GRPC_ARTICLE_SERVICE_ADDR=article-service:7171
      - HTTP_PORT=8080
    depends_on:
      user-service:
        condition: service_healthy
      article-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  user-service:
    image: your-user-service-image:latest
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:7373"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  article-service:
    image: your-article-service-image:latest
    ports:
      - "50052:50052"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:7171"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
